version: "3"
services: 
  kafka-consumer:
    build: ~/Kafka-mysql-consumer
    container_name: kafka-consumer
    restart : always
    volumes:
      - ~/Kafka-mysql-consumer:/opt
    environment: 
      TZ: "Aisa/Seoul"
    command: python3 -u /opt/run.py
